name: CI

on: [push]

jobs:
  build_windows_amd64:
    name: Build for Windows 64-bit
    runs-on: windows-2019
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.13.7'
      - name: Setup MSYS
        uses: numworks/setup-msys2@v1
        with:
          msystem: MINGW64
          path-type: inherit
          update: true
      - name: Install dependencies
        run: msys2do pacman --noconfirm -S --needed git base-devel mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake
      - name: Build artifacts
        env:
          PATH: ''
        run: msys2do make GOOS=windows GOARCH=amd64 setup
      - name: Hash artifacts
        run: sha256sum dist/*
        if: startsWith(github.ref, 'refs/tags/v')
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          name: buster-client-windows-amd64
          path: dist/
  build_windows_386:
    name: Build for Windows 32-bit
    runs-on: windows-2019
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.13.7'
      - name: Setup MSYS
        uses: numworks/setup-msys2@v1
        with:
          msystem: MINGW32
          path-type: inherit
          update: true
      - name: Install dependencies
        run: msys2do pacman --noconfirm -S --needed git base-devel mingw-w64-i686-toolchain mingw-w64-i686-cmake
      - name: Build artifacts
        env:
          PATH: ''
        run: msys2do make GOOS=windows GOARCH=386 setup
      - name: Hash artifacts
        run: sha256sum dist/*
        if: startsWith(github.ref, 'refs/tags/v')
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          name: buster-client-windows-386
          path: dist/
  build_linux_amd64:
    name: Build for Linux
    runs-on: ubuntu-18.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.13.7'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-dev xorg-dev libxtst-dev libpng++-dev xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev libxkbcommon-dev xsel xclip
      - name: Build artifacts
        run: make GOOS=linux GOARCH=amd64 setup
      - name: Hash artifacts
        run: sha256sum dist/*
        if: startsWith(github.ref, 'refs/tags/v')
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          name: buster-client-linux-amd64
          path: dist/
  build_macos_amd64:
    name: Build for macOS
    runs-on: macos-10.15
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.13.7'
      - name: Build artifacts
        run: make GOOS=darwin GOARCH=amd64 setup
      - name: Hash artifacts
        run: shasum -a 256 dist/*
        if: startsWith(github.ref, 'refs/tags/v')
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          name: buster-client-macos-amd64
          path: dist/
  release:
    name: Release on GitHub
    runs-on: ubuntu-18.04
    needs:
      [
        build_windows_amd64,
        build_windows_386,
        build_linux_amd64,
        build_macos_amd64,
      ]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Get release version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: buster-client-windows-amd64
          path: dist/
      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: buster-client-windows-386
          path: dist/
      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: buster-client-linux-amd64
          path: dist/
      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: buster-client-macos-amd64
          path: dist/
      - name: Hash artifacts
        run: sha256sum dist/*
      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@d9c9ca3
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: ${{ steps.get_version.outputs.VERSION }}
          body: |
            Learn more about this release from the [changelog](https://github.com/dessant/buster-client/blob/master/CHANGELOG.md#changelog).
          draft: true
      - name: Upload GitHub release assets
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/buster-client-setup-${{ steps.get_version.outputs.VERSION }}-windows-amd64.exe
          asset_name: buster-client-setup-${{ steps.get_version.outputs.VERSION }}-windows-amd64.exe
          asset_content_type: application/octet-stream
      - name: Upload GitHub release assets
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/buster-client-setup-${{ steps.get_version.outputs.VERSION }}-windows-386.exe
          asset_name: buster-client-setup-${{ steps.get_version.outputs.VERSION }}-windows-386.exe
          asset_content_type: application/octet-stream
      - name: Upload GitHub release assets
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/buster-client-setup-${{ steps.get_version.outputs.VERSION }}-linux-amd64
          asset_name: buster-client-setup-${{ steps.get_version.outputs.VERSION }}-linux-amd64
          asset_content_type: application/octet-stream
      - name: Upload GitHub release assets
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/buster-client-setup-${{ steps.get_version.outputs.VERSION }}-macos-amd64
          asset_name: buster-client-setup-${{ steps.get_version.outputs.VERSION }}-macos-amd64
          asset_content_type: application/octet-stream
